// <auto-generated />
using System;
using Facturacion.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Facturacion.Infrastructure.Migrations
{
    [DbContext(typeof(FacturacionContext))]
    partial class FacturacionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.Pantalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RutaPantalla")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Pantallas");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Pantallas_Nombre");

                    b.HasIndex("RutaPantalla")
                        .IsUnique()
                        .HasDatabaseName("UQ_Pantallas_RutaPantalla");

                    b.HasIndex("UsuarioCreacion");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("Pantallas", "Aut", t =>
                        {
                            t.HasCheckConstraint("CK_Pantallas_RutaPantalla", "[RutaPantalla] LIKE '/%'");
                        });
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Nombre");

                    b.HasIndex("UsuarioCreacion");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("Roles", "Aut", t =>
                        {
                            t.HasCheckConstraint("CK_Roles_Nombre", "LEN([Nombre]) >= 2");
                        });
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.RolPantalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PantallaId")
                        .HasColumnType("int");

                    b.Property<bool>("PuedeCrear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PuedeDeshabilitar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PuedeEditar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PuederVer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RolesPantallas");

                    b.HasIndex("PantallaId");

                    b.HasIndex("UsuarioCreacion");

                    b.HasIndex("UsuarioModificacion");

                    b.HasIndex("RolId", "PantallaId")
                        .IsUnique()
                        .HasDatabaseName("UQ_RolesPantallas_RolPantalla");

                    b.ToTable("RolesPantallas", "Aut");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuarios_Email");

                    b.HasIndex("UsuarioCreacion");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("Usuarios", "Aut", t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Email", "[Email] LIKE '%@%.%'");

                            t.HasCheckConstraint("CK_Usuarios_Nombre", "LEN([Nombre]) >= 2");

                            t.HasCheckConstraint("CK_Usuarios_UserName", "LEN([UserName]) >= 4");
                        });
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.UsuarioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_UsuariosRoles");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioCreacion");

                    b.HasIndex("UsuarioModificacion");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UsuariosRoles_UsuarioRol");

                    b.ToTable("UsuariosRoles", "Aut");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Clientes");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Clientes_Email");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Clientes_Identificacion");

                    b.HasIndex("UsuarioCreacion");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("Clientes", "Fac", t =>
                        {
                            t.HasCheckConstraint("CK_Clientes_Edad", "[Edad] >= 0 AND [Edad] <= 150");

                            t.HasCheckConstraint("CK_Clientes_Email", "[Email] LIKE '%@%.%'");

                            t.HasCheckConstraint("CK_Clientes_Identificacion", "LEN([Identificacion]) >= 5");

                            t.HasCheckConstraint("CK_Clientes_Nombre", "LEN([Nombre]) >= 2");
                        });
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Impuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Facturas");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioCreacion");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("Facturas", "Fac", t =>
                        {
                            t.HasCheckConstraint("CK_Facturas_Impuesto", "[Impuesto] >= 0");

                            t.HasCheckConstraint("CK_Facturas_Subtotal", "[Subtotal] >= 0");

                            t.HasCheckConstraint("CK_Facturas_Total", "[Total] >= 0");
                        });
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.FacturaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_FacturasDetalles");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioCreacion");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("FacturasDetalles", "Fac", t =>
                        {
                            t.HasCheckConstraint("CK_FacturasDetalles_Cantidad", "[Cantidad] >= 0");

                            t.HasCheckConstraint("CK_FacturasDetalles_PrecioUnitario", "[PrecioUnitario] >= 0");

                            t.HasCheckConstraint("CK_FacturasDetalles_SubTotal", "[SubTotal] >= 0");
                        });
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Productos");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Productos_Nombre");

                    b.HasIndex("UsuarioCreacion");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("Productos", "Fac", t =>
                        {
                            t.HasCheckConstraint("CK_Productos_Nombre", "LEN([Nombre]) >= 2");

                            t.HasCheckConstraint("CK_Productos_Precio", "[Precio] > 0");

                            t.HasCheckConstraint("CK_Productos_Stock", "[Stock] >= 0");
                        });
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.Pantalla", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Pantallas_UsuarioCrea");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioModf")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Pantallas_UsuarioModf");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModf");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.Rol", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Roles_UsuarioCrea");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioModf")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Roles_UsuarioModf");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModf");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.RolPantalla", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Pantalla", "Pantalla")
                        .WithMany("RolPantallas")
                        .HasForeignKey("PantallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolesPantallas_Pantallas");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Rol", "Rol")
                        .WithMany("rolPantallas")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolesPantallas_Roles");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RolesPantallas_UsuarioCrea");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioModf")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RolesPantallas_UsuarioModf");

                    b.Navigation("Pantalla");

                    b.Navigation("Rol");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModf");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.Usuario", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Usuarios_UsuarioCrea");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioModf")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Usuarios_UsuarioModf");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModf");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.UsuarioRol", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Rol", "Rol")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosRoles_Roles");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_UsuariosRoles_UsuarioCrea");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "Usuario")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosRoles_Usuarios");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioModf")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_UsuariosRoles_UsuarioModf");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModf");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.Cliente", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Clientes_UsuarioCrea");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioModf")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Clientes_UsuarioModf");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModf");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.Factura", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Facturacion.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Clientes");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Facturas_UsuarioCrea");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioModf")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Facturas_UsuarioModf");

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModf");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.FacturaDetalle", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Facturacion.Factura", "Factura")
                        .WithMany("FacturaDetalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FacturasDetalles_Facturas");

                    b.HasOne("Facturacion.Domain.Entities.Facturacion.Producto", "Producto")
                        .WithMany("FacturaDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FacturasDetalles_Productos");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_FacturasDetalles_UsuarioCrea");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioModf")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_FacturasDetalles_UsuarioModf");

                    b.Navigation("Factura");

                    b.Navigation("Producto");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModf");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.Producto", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Productos_UsuarioCrea");

                    b.HasOne("Facturacion.Domain.Entities.Autorizacion.Usuario", "UsuarioModf")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Productos_UsuarioModf");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModf");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.Pantalla", b =>
                {
                    b.Navigation("RolPantallas");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.Rol", b =>
                {
                    b.Navigation("UsuarioRols");

                    b.Navigation("rolPantallas");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Autorizacion.Usuario", b =>
                {
                    b.Navigation("UsuarioRols");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.Factura", b =>
                {
                    b.Navigation("FacturaDetalles");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Facturacion.Producto", b =>
                {
                    b.Navigation("FacturaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
